# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/super/OneDrive/Documents/VS/C&C++/Cube Cavern++"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/super/OneDrive/Documents/VS/C&C++/Cube Cavern++"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/super/OneDrive/Documents/VS/C&C++/Cube Cavern++/CMakeFiles" "/mnt/c/Users/super/OneDrive/Documents/VS/C&C++/Cube Cavern++//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/super/OneDrive/Documents/VS/C&C++/Cube Cavern++/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello_cpp_world

# Build rule for target.
hello_cpp_world: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_cpp_world
.PHONY : hello_cpp_world

# fast build rule for target.
hello_cpp_world/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/build
.PHONY : hello_cpp_world/fast

#=============================================================================
# Target rules for targets named hello_cpp_world-velf

# Build rule for target.
hello_cpp_world-velf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_cpp_world-velf
.PHONY : hello_cpp_world-velf

# fast build rule for target.
hello_cpp_world-velf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world-velf.dir/build.make CMakeFiles/hello_cpp_world-velf.dir/build
.PHONY : hello_cpp_world-velf/fast

#=============================================================================
# Target rules for targets named hello_cpp_world.self-self

# Build rule for target.
hello_cpp_world.self-self: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_cpp_world.self-self
.PHONY : hello_cpp_world.self-self

# fast build rule for target.
hello_cpp_world.self-self/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.self-self.dir/build.make CMakeFiles/hello_cpp_world.self-self.dir/build
.PHONY : hello_cpp_world.self-self/fast

#=============================================================================
# Target rules for targets named hello_cpp_world.vpk-vpk

# Build rule for target.
hello_cpp_world.vpk-vpk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_cpp_world.vpk-vpk
.PHONY : hello_cpp_world.vpk-vpk

# fast build rule for target.
hello_cpp_world.vpk-vpk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.vpk-vpk.dir/build.make CMakeFiles/hello_cpp_world.vpk-vpk.dir/build
.PHONY : hello_cpp_world.vpk-vpk/fast

Client/main_client.obj: Client/main_client.cpp.obj
.PHONY : Client/main_client.obj

# target to build an object file
Client/main_client.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/Client/main_client.cpp.obj
.PHONY : Client/main_client.cpp.obj

Client/main_client.i: Client/main_client.cpp.i
.PHONY : Client/main_client.i

# target to preprocess a source file
Client/main_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/Client/main_client.cpp.i
.PHONY : Client/main_client.cpp.i

Client/main_client.s: Client/main_client.cpp.s
.PHONY : Client/main_client.s

# target to generate assembly for a file
Client/main_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/Client/main_client.cpp.s
.PHONY : Client/main_client.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hello_cpp_world-velf"
	@echo "... hello_cpp_world.self-self"
	@echo "... hello_cpp_world.vpk-vpk"
	@echo "... hello_cpp_world"
	@echo "... Client/main_client.obj"
	@echo "... Client/main_client.i"
	@echo "... Client/main_client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

